version: '3.1'
services:
  db:
    build: ./mysql_zabbix
    restart: always
    volumes:
      - /dbdata:/var/lib/mysql
      - /dbconfig:/etc/mysql
      - /ftpdata:/ftpdata 
      - /dblogs:/var/log/mysql
    environment:
      TZ: "GMT-3"
      MYSQL_ROOT_PASSWORD: *****
    ports:
      - 3306:3306
      - 10050:10050
